### ISSUE TITLE
Why does this not have pricing for windows instances

### ISSUE THREAD

**Issue by NizamLZ** [banzaicloud/cloudinfo#254]
As we all know, windows instances have different pricing, is there any reason why windows instances pricing is not available here?

**Comment by lpuskas** [comment]
Hi NyamLZ,

We primarily use this service to support our other projects so the information we expose through the cloudinfo service is driven by the requirements of those projects.
(You can read more on this [here](https://banzaicloud.com/blog/cloud-provider-cloudinfo/))

While there are quite a lot of enhancements on our roadmap the timing and releasing of these depend on the other projects. 

If your use case requires additional information we are always open for PR's. Thanks.
