### ISSUE TITLE
Certain azure regions have 'unknown' continent

### ISSUE THREAD

**Issue by mrsheepuk** [banzaicloud/cloudinfo#353]
**Describe the bug**
Retrieving the continent/region map for Azure - AKS returns several regions in a continent named 'unknown'.

**Steps to reproduce the issue:**
See (e.g.) `https://banzaicloud.com/cloudinfo/api/v1/providers/azure/services/aks/continents`

**Expected behavior**
Regions are collected into continents.

**Screenshots**
Relevant part of the returned JSON:

```
[
    {
        "name": "unknown",
        "regions": [
            {
                "id": "switzerlandnorth",
                "name": "Switzerland North"
            },
            {
                "id": "switzerlandwest",
                "name": "Switzerland West"
            },
            {
                "id": "germanynorth",
                "name": "Germany North"
            },
            {
                "id": "norwayeast",
                "name": "Norway East"
            },
            {
                "id": "uaenorth",
                "name": "UAE North"
            },
            {
                "id": "germanywestcentral",
                "name": "Germany West Central"
            },
            {
                "id": "norwaywest",
                "name": "Norway West"
            }
        ]
    },
    ...
```

**Additional context**
Affects 0.13.0.

**Comment by sagikazarmark** [comment]
Unfortunately the [continent categorization algorithm](https://github.com/banzaicloud/cloudinfo/blob/00eb0ece4a8c0457b7b181c7879e1d510c81a76a/internal/cloudinfo/cloudinfo.go#L204-L230) is pretty dumb.

The best solution would be an API from the cloud providers themselves, so we don't have to update code when they add new regions.

I guess adding a map with all the regions would be a better/easier to maintain until they introduce an API like that (which I doubt they will).

Are you up for a PR or should we grab it?

**Comment by mrsheepuk** [comment]
I'll take a look at it soon if I get time, but likely be a few days - I won't complain if you go ahead :)

**Comment by sagikazarmark** [comment]
Okay. I'll let you know if I get there.

**Comment by mrsheepuk** [comment]
Taking a quick look at this now @sagikazarmark FYI.

**Comment by mrsheepuk** [comment]
@sagikazarmark I've raised a PR for this one - no attempt to make it any cleverer, just adding the missing pattern matches for now. Let me know if it looks OK!

**Comment by sagikazarmark** [comment]
Thanks!
