### ISSUE TITLE
No instance types returned for any Europe regions on AWS

### ISSUE THREAD

**Issue by mrsheepuk** [banzaicloud/cloudinfo#365]
**Describe the bug**
All European regions on AWS now return no instance types - see log message `numberOfVms: 0`:

```
{"application":"cloudinfo","environment":"production","level":"debug","msg":"getting available instance types from AWS API","provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
{"application":"cloudinfo","environment":"production","level":"debug","missingAttrs":{},"msg":"instance types with missing attributes","provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
{"application":"cloudinfo","environment":"production","level":"debug","missingGPU":null,"msg":"instance types with missing gpu","provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
{"application":"cloudinfo","environment":"production","level":"debug","msg":"couldn't find any virtual machines to recommend","provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
{"application":"cloudinfo","environment":"production","level":"debug","msg":"found vms","numberOfVms":0,"provider":"amazon","region":"eu-west-1","time":"2020-08-05T09:38:42Z"}
```

This is almost certainly caused by the [AWS SDK upgrade PR](https://github.com/banzaicloud/cloudinfo/pull/345) - noting specifically [this change in the expected region descriptions](https://github.com/banzaicloud/cloudinfo/pull/345/files#diff-b5c2ebb285b93f9707ce8481530ed2f5L180-R181) - the pricing API still uses 'EU' not 'Europe' in its location field, so this now will not match any European instances:

```
aws --region us-east-1 pricing get-attribute-values --service-code AmazonEC2 --attribute-name location --output table

----------------------------------
|       GetAttributeValues       |
+--------------------------------+
||        AttributeValues       ||
|+------------------------------+|
||             Value            ||
|+------------------------------+|
||  AWS GovCloud (US-East)      ||
||  AWS GovCloud (US-West)      ||
||  Africa (Cape Town)          ||
||  Asia Pacific (Hong Kong)    ||
||  Asia Pacific (Mumbai)       ||
||  Asia Pacific (Osaka-Local)  ||
||  Asia Pacific (Seoul)        ||
||  Asia Pacific (Singapore)    ||
||  Asia Pacific (Sydney)       ||
||  Asia Pacific (Tokyo)        ||
||  Canada (Central)            ||
||  EU (Frankfurt)              ||
||  EU (Ireland)                ||
||  EU (London)                 ||
||  EU (Milan)                  ||
||  EU (Paris)                  ||
||  EU (Stockholm)              ||
||  Middle East (Bahrain)       ||
||  South America (Sao Paulo)   ||
||  US East (N. Virginia)       ||
||  US East (Ohio)              ||
||  US West (Los Angeles)       ||
||  US West (N. California)     ||
||  US West (Oregon)            ||
|+------------------------------+|
```

**Steps to reproduce the issue:**
run cloudinfo with AWS enabled

**Additional context**
Tested on latest tagged `0.15.0`

**Comment by sagikazarmark** [comment]
I might be mistaken, but we got bitten by this a while ago, and the SDK upgrade seemingly solved the issue. Did AWS change it *back*?

**Comment by mrsheepuk** [comment]
> I might be mistaken, but we got bitten by this a while ago, and the SDK upgrade seemingly solved the issue. Did AWS change it _back_?

I wouldn't be surprised! It'll probably change at some point again.

_mumbles something about bloody brexit breaking everything_

Thanks for the super-quick fix!

**Comment by sagikazarmark** [comment]
> _mumbles something about bloody brexit breaking everything_

🤣 

Yeah, I'll try to add a fix that supports both versions.

> Thanks for the super-quick fix!

As part of the release process I'll deploy it to our test env, test it there and then tag 0.15.1 if it works well.

**Comment by sagikazarmark** [comment]
See #36

**Comment by mrsheepuk** [comment]
My reading of the filter spec for the pricing API is that the filters are ANDed, so trying to make it support both could be tricky - I guess calling with one filter then if nothing is returned, calling with the other would solve it.

... while I was typing this, I see you've put the same concept in #367 :+1:
