### ISSUE TITLE
cloudinfo setup error

### ISSUE THREAD

**Issue by Adilshaikh8003** [banzaicloud/cloudinfo#374]
**Describe the bug**
1. I have uploaded code on the ubuntu server and followed the steps which present in readme file. 

**Steps to reproduce the issue:**
1. after updating the config.toml file for AWS credential. 
2. We able to build the project below errors are come out
 
vinod@cloudinfo:/opt/cloudinfo/cmd/cloudinfo$ go run vars.go config.go main.go
{"application":"cloudinfo","environment":"production","level":"warning","msg":"configuration file not found","time":"2020-08-14T14:55:22Z"}
{"application":"cloudinfo","arch":"amd64","build_date":"","commit_hash":"","compiler":"gc","environment":"production","go_version":"go1.14.6","level":"info","msg":"starting application","os":"linux","time":"2020-08-14T14:55:22Z","version":""}
{"application":"cloudinfo","environment":"production","level":"info","msg":"using in-mem cache as product store","time":"2020-08-14T14:55:22Z"}
{"application":"cloudinfo","environment":"production","level":"error","msg":"Config File \"services\" Not Found in \"[/opt/cloudinfo/cmd/cloudinfo/configs]\"","time":"2020-08-14T14:55:22Z"}
vinod@cloudinfo:/opt/cloudinfo/cmd/cloudinfo$

Please let me know where I will get these below config parameters. (Does it requires banzaicloud account?)
      --config-vault string               enable config Vault
      --config-vault-address string       config Vault address
      --config-vault-token string         config Vault token
      --config-vault-secret-path string   config Vault secret path
      --log-level string                  log level (default "info")
      --log-format string                 log format (default "json")
      --metrics-enabled                   internal metrics are exposed if enabled

 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lpuskas** [comment]
Hi @Adilshaikh8003, based on your logs it seems that the configuration file is not found. Please make sure you point the app to the location where you put your configuration file (specify it with the `--config` argument)

By default you don't need to specify the values you listed; the minimal configuration is only the provider and related credentials. (no Banzai Cloud account is required)
