### ISSUE TITLE
Cloudinfo azure credential issue

### ISSUE THREAD

**Issue by Adilshaikh8003** [banzaicloud/cloudinfo#377]
**Describe the bug**
{"application":"cloudinfo","arch":"amd64","build_date":"2020-09-08T14:37:44+0530","commit_hash":"38061e4","compiler":"gc","environment":"production","go_version":"go1.14.6","level":"info","msg":"starting application","os":"windows","time":"2020-09-08T14:38:08+05:30","version":"master"}
{"application":"cloudinfo","environment":"production","level":"info","msg":"using in-mem cache as product store","time":"2020-09-08T14:38:08+05:30"}
{"application":"cloudinfo","environment":"production","level":"info","msg":"configured cloud info provider","provider":"azure","time":"2020-09-08T14:38:08+05:30"}
{"application":"cloudinfo","component":"service-manager","environment":"production","level":"info","msg":"triggering cloud information importing ...","time":"2020-09-08T14:38:08+05:30"}
{"application":"cloudinfo","component":"service-manager","environment":"production","level":"info","msg":"cloud information imported.","time":"2020-09-08T14:38:08+05:30"}
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /management/store/export  --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/management.(*mngmntRouteHandler).Export.func1 (1 handlers)
[GIN-debug] PUT    /management/store/import  --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/management.(*mngmntRouteHandler).Import.func1 (1 handlers)
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] PUT    /management/store/refresh/:provider --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/management.(*mngmntRouteHandler).Refresh.func1 (1 handlers)
[GIN-debug] Listening and serving HTTP on :8001
{"application":"cloudinfo","component":"scraping-manager","environment":"production","level":"info","msg":"start scraping for provider information","provider":"azure","time":"2020-09-08T14:38:08+05:30"}
{"application":"cloudinfo","environment":"production","level":"info","msg":"configuring routes","time":"2020-09-08T14:38:08+05:30"}
{"application":"cloudinfo","component":"scraping-manager","environment":"production","level":"info","msg":"initializing cloud product information","provider":"azure","time":"2020-09-08T14:38:08+05:30"}
[GIN-debug] GET    /                         --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).ConfigureRoutes.func1 (7 handlers)
[GIN-debug] GET    /index.html               --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).ConfigureRoutes.func2 (7 handlers)
[GIN-debug] GET    /status                   --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).signalStatus-fm (7 handlers)
[GIN-debug] GET    /version                  --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).versionHandler-fm (7 handlers)
[GIN-debug] GET    /api/v1/continents        --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getContinents.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/        --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getProviders.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getProvider.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider/services --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getServices.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider/services/:service --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getService.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider/services/:service/continents --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getContinentsData.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider/services/:service/regions --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getRegions.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider/services/:service/regions/:region --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getRegion.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider/services/:service/regions/:region/images --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getImages.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider/services/:service/regions/:region/versions --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getVersions.func1 (7 handlers)
[GIN-debug] GET    /api/v1/providers/:provider/services/:service/regions/:region/products --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).getProducts.func1 (7 handlers)
[GIN-debug] POST   /graphql                  --> github.com/banzaicloud/cloudinfo/internal/app/cloudinfo/api.(*RouteHandler).query.func1 (7 handlers)
[GIN-debug] Listening and serving HTTP on :8000
{"application":"cloudinfo","environment":"production","level":"error","msg":"error while retrieving azure locations","provider":"azure","service":"compute","time":"2020-09-08T14:38:08+05:30"}
{"application":"cloudinfo","component":"scraping-manager","environment":"production","level":"error","msg":"failed to initialize cloud product information","provider":"azure","time":"2020-09-08T14:38:08+05:30"}
panic: runtime error: comparing uncomparable type autorest.DetailedError

goroutine 10 [running]:
emperror.dev/handler/logur.(*Handler).Handle(0xc0002feff0, 0x2bb6c40, 0xc000160000)
        C:/Users/User/go/pkg/mod/emperror.dev/handler/logur@v0.4.0/handler.go:94 +0x46b
github.com/banzaicloud/cloudinfo/internal/cloudinfo.(*scrapingManager).initialize(0xc00055fb80, 0x2c00600, 0xc0000340c8)
        D:/cloudinfo/internal/cloudinfo/scrape.go:54 +0x566
github.com/banzaicloud/cloudinfo/internal/cloudinfo.(*scrapingManager).scrape(0xc00055fb80, 0x2c00600, 0xc0000340c8)
        D:/cloudinfo/internal/cloudinfo/scrape.go:303 +0x299
created by github.com/banzaicloud/cloudinfo/internal/cloudinfo.(*ScrapingDriver).renewAll
        D:/cloudinfo/internal/cloudinfo/scrape.go:371 +0x7c

**Steps to reproduce the issue:**
1. We able to make build and its running port 8000 but facing the above issue.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sagikazarmark** [comment]
Chances are it's caused by wrong azure credentials

**Comment by Adilshaikh8003** [comment]
Can you please share the steps for azure credentials? It will help us to fix the issue.

**Comment by sagikazarmark** [comment]
It's in the documentation: https://github.com/banzaicloud/cloudinfo#azure

**Comment by bandesz** [comment]
Was this fixed? Even if the Azure credentials are wrong, the app shouldn't crash like this. We are using 0.16.0.

**Comment by sagikazarmark** [comment]
Yeah, it shouldn't. PRs (or issues) are welcome :)

**Comment by bandesz** [comment]
@sagikazarmark can you please re-open this issue as this wasn't fixed. We'll see if we have the time to submit a fix PR, but this might affect your product offerings too.

**Comment by bandesz** [comment]
Note: we've encountered this issue when the password was incorrect on the service principal.

**Comment by sagikazarmark** [comment]
@bandesz I've opened a new issue with a better description: #384
